### ISSUE TITLE
Plot af FS diff_diff forkert 

### ISSUE THREAD

**Issue by majbrittws** [TanyaPS/Nojagtighedstest#5]
Df med fs_Leica_dd og fs_Trimble_dd er formodentlig forkert. Det er i hvert fald ikke det korrekte der vises, når jeg prøver at plotte forskellen ml. 1. og 2. fast static-måling i en barplot..

**Comment by majbrittws** [comment]
Ahr, dumt! Det var fordi jeg brugte den forkerte parameter.... Sorry!.. Det skal være "til_2.måling" og ikke "Difference"...

**Comment by TanyaPS** [comment]
ja det nåede jeg også at se, var igang med at tjekke om de andre parametre efter :)
